export type PricingItem = {
  id: string
  upc: string
  name: string
  category: string
  importCost: number
  shippingCost: number
  customsDuty: number
  handlingFee: number
  costPrice: number
  salePrice: number
  netProfit: number
  profitMargin: number
  vendor: string
  inStock: number
}

export const categories = [
  "Air Pistols",
  "Air Rifles",
  "CO2 Capsules",
  "Ammunition",
  "Scopes & Sights",
  "Accessories",
  "Parts & Service",
]

export const pricingData: PricingItem[] = [
  {
    id: "1",
    upc: "UX-AP-001",
    name: "Umarex Glock 17 Gen5",
    category: "Air Pistols",
    importCost: 45.0,
    shippingCost: 3.5,
    customsDuty: 4.2,
    handlingFee: 2.0,
    costPrice: 54.7,
    salePrice: 89.99,
    netProfit: 35.29,
    profitMargin: 39.22,
    vendor: "Umarex Germany",
    inStock: 24,
  },
  {
    id: "2",
    upc: "UX-AP-002",
    name: "Umarex Beretta 92FS",
    category: "Air Pistols",
    importCost: 42.5,
    shippingCost: 3.5,
    customsDuty: 4.0,
    handlingFee: 2.0,
    costPrice: 52.0,
    salePrice: 84.99,
    netProfit: 32.99,
    profitMargin: 38.82,
    vendor: "Umarex Germany",
    inStock: 18,
  },
  {
    id: "3",
    upc: "UX-AR-001",
    name: "Umarex Ruger 10/22",
    category: "Air Rifles",
    importCost: 85.0,
    shippingCost: 7.5,
    customsDuty: 8.2,
    handlingFee: 3.0,
    costPrice: 103.7,
    salePrice: 169.99,
    netProfit: 66.29,
    profitMargin: 39.0,
    vendor: "Umarex Germany",
    inStock: 12,
  },
  {
    id: "4",
    upc: "UX-AR-002",
    name: "Umarex Hämmerli CR20",
    category: "Air Rifles",
    importCost: 110.0,
    shippingCost: 9.0,
    customsDuty: 10.5,
    handlingFee: 3.5,
    costPrice: 133.0,
    salePrice: 219.99,
    netProfit: 86.99,
    profitMargin: 39.54,
    vendor: "Umarex Germany",
    inStock: 8,
  },
  {
    id: "5",
    upc: "UX-CO2-001",
    name: "Umarex CO2 Capsules (10pk)",
    category: "CO2 Capsules",
    importCost: 3.2,
    shippingCost: 0.8,
    customsDuty: 0.4,
    handlingFee: 0.2,
    costPrice: 4.6,
    salePrice: 7.99,
    netProfit: 3.39,
    profitMargin: 42.43,
    vendor: "Umarex Germany",
    inStock: 120,
  },
  {
    id: "6",
    upc: "UX-CO2-002",
    name: "Umarex CO2 Capsules (25pk)",
    category: "CO2 Capsules",
    importCost: 7.5,
    shippingCost: 1.2,
    customsDuty: 0.8,
    handlingFee: 0.3,
    costPrice: 9.8,
    salePrice: 16.99,
    netProfit: 7.19,
    profitMargin: 42.32,
    vendor: "Umarex Germany",
    inStock: 85,
  },
  {
    id: "7",
    upc: "UX-AM-001",
    name: "Umarex Steel BBs (1500ct)",
    category: "Ammunition",
    importCost: 4.8,
    shippingCost: 1.0,
    customsDuty: 0.5,
    handlingFee: 0.2,
    costPrice: 6.5,
    salePrice: 10.99,
    netProfit: 4.49,
    profitMargin: 40.86,
    vendor: "Umarex Germany",
    inStock: 65,
  },
  {
    id: "8",
    upc: "UX-AM-002",
    name: "Umarex .177 Pellets (500ct)",
    category: "Ammunition",
    importCost: 5.2,
    shippingCost: 1.0,
    customsDuty: 0.6,
    handlingFee: 0.2,
    costPrice: 7.0,
    salePrice: 11.99,
    netProfit: 4.99,
    profitMargin: 41.62,
    vendor: "Umarex Germany",
    inStock: 42,
  },
  {
    id: "9",
    upc: "UX-SS-001",
    name: "Walther 2x20 Scope",
    category: "Scopes & Sights",
    importCost: 28.5,
    shippingCost: 2.5,
    customsDuty: 2.8,
    handlingFee: 1.5,
    costPrice: 35.3,
    salePrice: 59.99,
    netProfit: 24.69,
    profitMargin: 41.16,
    vendor: "Walther",
    inStock: 15,
  },
  {
    id: "10",
    upc: "UX-SS-002",
    name: "Umarex Red Dot Sight",
    category: "Scopes & Sights",
    importCost: 32.0,
    shippingCost: 2.5,
    customsDuty: 3.0,
    handlingFee: 1.5,
    costPrice: 39.0,
    salePrice: 64.99,
    netProfit: 25.99,
    profitMargin: 39.99,
    vendor: "Umarex Germany",
    inStock: 10,
  },
  {
    id: "11",
    upc: "UX-AC-001",
    name: "Umarex Gun Case (Small)",
    category: "Accessories",
    importCost: 12.5,
    shippingCost: 2.0,
    customsDuty: 1.3,
    handlingFee: 0.8,
    costPrice: 16.6,
    salePrice: 27.99,
    netProfit: 11.39,
    profitMargin: 40.69,
    vendor: "Umarex Germany",
    inStock: 22,
  },
  {
    id: "12",
    upc: "UX-AC-002",
    name: "Umarex Cleaning Kit",
    category: "Accessories",
    importCost: 8.2,
    shippingCost: 1.5,
    customsDuty: 0.9,
    handlingFee: 0.6,
    costPrice: 11.2,
    salePrice: 19.99,
    netProfit: 8.79,
    profitMargin: 43.97,
    vendor: "Umarex Germany",
    inStock: 30,
  },
  {
    id: "13",
    upc: "UX-PS-001",
    name: "Glock 17 Trigger Spring",
    category: "Parts & Service",
    importCost: 2.1,
    shippingCost: 0.3,
    customsDuty: 0.2,
    handlingFee: 0.1,
    costPrice: 2.7,
    salePrice: 5.99,
    netProfit: 3.29,
    profitMargin: 54.92,
    vendor: "Umarex Germany",
    inStock: 45,
  },
  {
    id: "14",
    upc: "UX-PS-002",
    name: "CO2 Valve Repair Kit",
    category: "Parts & Service",
    importCost: 4.8,
    shippingCost: 0.5,
    customsDuty: 0.4,
    handlingFee: 0.2,
    costPrice: 5.9,
    salePrice: 12.99,
    netProfit: 7.09,
    profitMargin: 54.58,
    vendor: "Umarex Germany",
    inStock: 25,
  },
]
